added user and auth resources
obscurezz/coursework_flask_api pull request #2
Opened 2022-08-18 07:30 UTC by obscurezz

1. Auth decorator
2. Auth/user services and views

2022-08-18 08:17 UTC, painassasin requested changes

2022-08-18 08:17 UTC, painassasin commented on project/services/auth/auth_service.py
> +from flask import abort, current_app
Чем abort от Flask отличается от abort из flask-restx? Может лучше поюзать его?

2022-08-18 08:17 UTC, painassasin commented on project/services/auth/auth_service.py
> +        data['exp'] = calendar.timegm(days30.timetuple())
Код повторяется, просто с разными аргументами - может в функцию?

2022-08-18 08:17 UTC, painassasin commented on project/services/auth/auth_service.py
> +        return {
Давай тут тоже будем возвращать модель pydantic

2022-08-18 08:17 UTC, painassasin commented on project/tools/decorators.py
> +        return func(current_user, *args, **kwargs)
Лучше отдавать не позиционным, а именованным аргументом

2022-08-18 09:27 UTC, obscurezz commented on project/services/auth/auth_service.py
> +from flask import abort, current_app
Давай поюзаем его. Поставил.

2022-08-18 09:30 UTC, obscurezz commented on project/services/auth/auth_service.py
> +        data['exp'] = calendar.timegm(days30.timetuple())
https://github.com/obscurezz/coursework_flask_api/blob/2c876f641a4955bf6df41252ebbd323d3e828321/project/services/auth/auth_service.py#L18-L28

2022-08-18 09:31 UTC, obscurezz commented on project/services/auth/auth_service.py
> +        return {
https://github.com/obscurezz/coursework_flask_api/blob/2c876f641a4955bf6df41252ebbd323d3e828321/project/services/auth/auth_service.py#L43-L48
https://github.com/obscurezz/coursework_flask_api/blob/2c876f641a4955bf6df41252ebbd323d3e828321/project/models.py#L53-L55

2022-08-18 09:32 UTC, obscurezz commented on project/tools/decorators.py
> +        return func(current_user, *args, **kwargs)
https://github.com/obscurezz/coursework_flask_api/blob/2c876f641a4955bf6df41252ebbd323d3e828321/project/tools/decorators.py#L21

2022-08-18 19:44 UTC, painassasin requested changes

2022-08-18 19:44 UTC, painassasin commented on project/dao/base_dao.py
> +        self._db_session.close()
Зачем тут закрываешь сессию?
Я же вроде показывал в разборе как нужно их использовать

2022-08-18 19:44 UTC, painassasin commented on project/models.py
> +    access_token: str = Field(regex='(^[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*$)')
Такого я еще не видел) Но в целом норм!

2022-08-18 19:44 UTC, painassasin commented on project/orm_models/orm_models.py
>          CheckConstraint("email LIKE '%___@___%.__%'"),
И что работает? Я бы тут регулярку закинул лучше

2022-08-18 19:44 UTC, painassasin commented on project/services/auth/auth_service.py
> +        self.user_service = user_service
Зачем нам его передвать в аргументах, если мы сразу его можем получить? К тому же судя по тайпхинту кроме этого сервиса сюда ничего больше положить нельзя

2022-08-18 19:44 UTC, painassasin commented on project/services/auth/auth_service.py
> +        def create_token(timer: str, value: int, data: dict) -> str:
Функция в функции - плохая идея. Сложно протестировать потом. Лучше сделать ее методом класса, статическим, _create_token

2022-08-18 19:44 UTC, painassasin commented on project/services/auth/auth_service.py
> +                return 'Wrong time input'
Тут лучше подойдет `raise ValueError`

2022-08-18 19:44 UTC, painassasin commented on project/services/auth/auth_service.py
> +        access_token = create_token('min', 30, data)
Я думаю сюда лучше передавать сразу объект timedelta и вообще хранить его в настройках приложения, потому, что, например при написании тех же тестов, нам хотелось бы глобально управлять этими настройками, а не иметь "хардкод".

2022-08-18 19:44 UTC, painassasin commented on project/setup/api/__init__.py
> +    version='1.01',
Если хочешь использовать версионирование - используй человеческое)
0.2.0 - тут нужно поменять минорную версию, т.к. добавился функционал

2022-08-18 19:44 UTC, painassasin commented on project/tools/decorators.py
>      def decorator(*args, **kwargs):
```python
@wraps(func)
def decorator(*args, **kwargs):
  ...

2022-08-18 19:44 UTC, painassasin commented on project/tools/decorators.py
>              return {'Exception': e}
`return` после `abort`? - что-то новенькое

2022-08-18 19:44 UTC, painassasin commented on project/views/auth/user_view.py
> +        user: dict = user_service.get_user_by_email_and_password(email=username)
`email = username`? как-то не логично

2022-08-18 19:44 UTC, painassasin commented on project/views/auth/user_view.py
> +    def get(username):
и вообще - ты же используешь pydantic - почему бы не создать модель, которую ты будешь хранить в токене и ее сюда пробрасывать. Тогда ты будешь знать и id и email и другие "открытые" параметры пользователя

2022-08-18 19:45 UTC, painassasin approved these changes

2022-08-19 03:18 UTC, obscurezz commented on project/orm_models/orm_models.py
>          CheckConstraint("email LIKE '%___@___%.__%'"),
Работает.
А вот с регуляркой у меня пока не вышло. И с регуляркой в модели pydantic для пароля тоже. Но я добью этот вопрос)

2022-08-19 03:34 UTC, obscurezz commented on project/views/auth/user_view.py
> +        user: dict = user_service.get_user_by_email_and_password(email=username)
Ну типа юзернейм пользака - это его ящик. Я и сам уже запутался)
Поставил везде email, никаких юзернеймов)

2022-08-19 03:50 UTC, obscurezz commented on project/dao/base_dao.py
> +        self._db_session.close()
Я видимо этот QA пропустил(
На самом деле это как раз та ситуация, о которой я говорил вчера. У нас есть сервис, который:
1) Получает юзера по id
2) При успешной проверке выполняет ему апдейт.
https://github.com/obscurezz/coursework_flask_api/blob/ba91daf911f0617b1aa208a0c7503119e8bfbb0b/project/services/auth/user_service.py#L61-L77
И у меня в текущей реализации кода в этом случае может возникать 2 различных проблемы:
1) Сессии селектов принудительно не закрыты, subtransactions не включены - возникает ошибка алхимии:
a transaction is already begun on this session
Выглядит логично, сессия селекта не закрыта, есть активная транзакция, поэтому апдейт запустить нельзя.
2) Сессии селектов принудительно не закрыты, subtransactions включены - ошибок не возникает (потому что мы запускаем транзакцию апдейта в том же begin/end, что и селекта), но при этом изменения не накатываются на БД, потому что при закрытии сессии у нас LIFO и т.к. селект первый, то закрывается он последним, принося с собой роллбэк.
Поэтому мне помогло принудительное завершение сессий селектов и отключение сабтранзакций.
Вчера ты объяснил, что сессии неплохо бы перенести либо в сервисы, либо во вьюхи через g, но я пока с этим не разобрался. А в твоей базовой реализации сессия передается в ДАО)

2022-08-19 04:11 UTC, obscurezz commented on project/services/auth/auth_service.py
> +        self.user_service = user_service
Получить из контейнера? circular import
Если получать пустой сервис, который зависит от DAO, то нам придется в файл auth_service импортировать UserService, UserDAO и db, чтобы дать на вход ДАО сессию. А это тоже может привести к циклическому импорту.

2022-08-19 04:14 UTC, obscurezz commented on project/services/auth/auth_service.py
> +                return 'Wrong time input'
С передачей в функцию аргументов из конфига с тайпхинтингом на timedelta в этом вообще отпала нужда.

2022-08-19 04:14 UTC, obscurezz commented on project/setup/api/__init__.py
> +    version='1.01',
Не шарю в этом вообще)
Сделал 0.2.0

2022-08-19 04:14 UTC, obscurezz commented on project/tools/decorators.py
>              return {'Exception': e}
Брейнлаг)

2022-08-19 04:39 UTC, obscurezz commented on project/views/auth/user_view.py
> +    def get(username):
Я примерно понял, что ты имеешь в виду, но пока не сообразил с реализацией. Попробую)

2022-08-19 05:02 UTC, obscurezz commented on project/services/auth/auth_service.py
> +        def create_token(timer: str, value: int, data: dict) -> str:
https://github.com/obscurezz/coursework_flask_api/blob/e89a5a1f2fb1a10fdeaaf7673a625684e895cc67/project/services/auth/auth_service.py#L17-L27

2022-08-19 05:02 UTC, obscurezz commented on project/services/auth/auth_service.py
> +        access_token = create_token('min', 30, data)
https://github.com/obscurezz/coursework_flask_api/blob/e89a5a1f2fb1a10fdeaaf7673a625684e895cc67/project/config.py#L32-L34

2022-08-19 05:03 UTC, obscurezz commented on project/tools/decorators.py
>      def decorator(*args, **kwargs):
Done

2022-08-19 15:59 UTC, painassasin commented on project/services/auth/auth_service.py
> +        return {
А почему не модель то возвращаешь? Зачем словарем? В этом и смысл был в pydantic - что ты возвращаешь определенную структуру, а не просто словарь с непонятным набором ключей

2022-08-19 16:00 UTC, painassasin commented on project/dao/base_dao.py
> +        self._db_session.close()
Посмотри разбор - у тебя должна быть одна сессия на запрос, а ошибка падает потому, что сессия закрывается, после выхода из DAO

2022-08-19 16:02 UTC, painassasin commented on project/services/auth/auth_service.py
> +        self.user_service = user_service
Так тоже не работает?
```python
self.user_service  = UserService()
```

2022-08-19 16:11 UTC, merged